theme:
  activeBorderColor:
    - '#73DACA'
    - bold
  inactiveBorderColor:
    - '#C0CAF5'
  optionsTextColor:
    - '#7AA2F7'
  selectedLineBgColor:
    - '#7AA2F7'
  cherryPickedCommitBgColor:
    - '#7DCFFF'
  cherryPickedCommitFgColor:
    - '#7AA2F7'
  unstagedChangesColor:
    - '#F7768E'
  defaultFgColor:
    - '#CCCCCC'
  searchingActiveBorderColor:
    - '#7DCFFF'
    - bold

authorColors:
  '*': '#BB9AF7'
