add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$character\
"""

[directory]
style = "blue"

[character]
success_symbol = "[ ❯](purple)"
error_symbol = "[ ❯](red)"
vimcmd_symbol = "[ ❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "purple"

[git_status]
format = '( [\[$all_status$ahead_behind\]](red))'
